OrdererOrgs:
  - Name: Orderer
    Domain: yzm.com
    EnableNodeOUs: true # 控制节点目录中是否生成配置文件
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: OrgA
    Domain: orga.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OrgB
    Domain: orgb.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
