version: '2'
services:
  orderer0.yzm.com:
    container_name: orderer0.trace.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6050
        - PBFT_LISTEN_PORT=26070
        - PBFT_NODE_ID=0
        - PBFT_NODE_TABLE=http://orderer0.yzm.com:26070;http://orderer1.yzm.com:26071;http://orderer2.yzm.com:26072;http://orderer3.yzm.com:26073
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer0.yzm.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer0.yzm.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer0
    ports:
      - 6050:6050
      - 26070:26070

  orderer1.yzm.com:
    container_name: orderer1.trace.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6051
        - PBFT_LISTEN_PORT=26071
        - PBFT_NODE_ID=1
        - PBFT_NODE_TABLE=http://orderer0.yzm.com:26070;http://orderer1.yzm.com:26071;http://orderer2.yzm.com:26072;http://orderer3.yzm.com:26073
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer1.yzm.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer1.yzm.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer1
    ports:
      - 6051:6051
      - 26071:26071

  orderer2.yzm.com:
    container_name: orderer2.trace.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6052
        - PBFT_LISTEN_PORT=26072
        - PBFT_NODE_ID=2
        - PBFT_NODE_TABLE=http://orderer0.yzm.com:26070;http://orderer1.yzm.com:26071;http://orderer2.yzm.com:26072;http://orderer3.yzm.com:26073
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer2.yzm.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer2.yzm.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer2
    ports:
      - 6052:6052
      - 26072:26072

  orderer3.yzm.com:
    container_name: orderer3.trace.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LISTENPORT=6053
        - PBFT_LISTEN_PORT=26073
        - PBFT_NODE_ID=3
        - PBFT_NODE_TABLE=http://orderer0.yzm.com:26070;http://orderer1.yzm.com:26071;http://orderer2.yzm.com:26072;http://orderer3.yzm.com:26073
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer3.yzm.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/yzm.com/orderers/orderer3.yzm.com/tls:/var/hyperledger/orderer/tls
        - ../production/orderer:/var/hyperledger/production/orderer3
    ports:
      - 6053:6053
      - 26073:26073

  peer0.orga.com:
    container_name: peer0.orga.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orga.com
      - CORE_PEER_ADDRESS=peer0.orga.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orga.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orga.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orga.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orga.com/peers/peer0.orga.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orga.com/peers/peer0.orga.com/tls:/etc/hyperledger/fabric/tls
        - ../production/orga0:/var/hyperledger/production

    ports:
      - 7051:7051

  peer1.orga.com:
    container_name: peer1.orga.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orga.com
      - CORE_PEER_ADDRESS=peer1.orga.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.orga.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orga.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orga.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orga.com/peers/peer1.orga.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orga.com/peers/peer1.orga.com/tls:/etc/hyperledger/fabric/tls
        - ../production/orga1:/var/hyperledger/production

    ports:
      - 7151:7051

  peer2.orga.com:
    container_name: peer2.orga.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.orga.com
      - CORE_PEER_ADDRESS=peer2.orga.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer2.orga.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.orga.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.orga.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orga.com/peers/peer2.orga.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orga.com/peers/peer2.orga.com/tls:/etc/hyperledger/fabric/tls
        - ../production/orga2:/var/hyperledger/production

    ports:
      - 7251:7051

  peer3.orga.com:
    container_name: peer3.orga.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.orga.com
      - CORE_PEER_ADDRESS=peer3.orga.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer3.orga.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.orga.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.orga.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orga.com/peers/peer3.orga.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orga.com/peers/peer3.orga.com/tls:/etc/hyperledger/fabric/tls
        - ../production/orga3:/var/hyperledger/production

    ports:
      - 7351:7051

  peer4.orga.com:
    container_name: peer4.orga.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer4.orga.com
      - CORE_PEER_ADDRESS=peer4.orga.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer4.orga.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer4.orga.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.orga.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orga.com/peers/peer4.orga.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orga.com/peers/peer4.orga.com/tls:/etc/hyperledger/fabric/tls
        - ../production/orga4:/var/hyperledger/production

    ports:
      - 7451:7051


